---
# Elasticsearch
elasticsearch_repository:
  yum: 'https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/yum'
  apt: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'

elasticsearch_version: '7.x'
elasticsearch_config_template: elasticsearch.yml.j2
elasticsearch_config_file_path: /etc/elasticsearch/elasticsearch.yml
elasticsearch_host: ''
elasticsearch_port: ''
elasticsearch_extra_options: ''

# Kinaba
kibana_repository:
  yum: 'https://artifacts.elastic.co/packages/{{ kibana_version }}/yum'
  apt: 'deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main'

kibana_version: '7.x'
kibana_config_template: kibana.yml.j2
kibana_config_file_path: /etc/kibana/kibana.yml
kibana_server_port: ''
kibana_server_host: ''
kibana_elasticsearch_url: ''
kibana_elasticsearch_username: ''
kibana_elasticsearch_password: ''