---
- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    shell: /sbin/nologin
    state: present

- name: Download and unarchive node_exporter
  ansible.builtin.unarchive:
    src: '{{ node_exporter_tar_link }}'
    dest: /tmp
    mode: 0644
    remote_src: true

- name: Copy node_exporter binary
  ansible.builtin.copy:
    src: '/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter'
    dest: '{{ node_exporter_bin_path }}'
    owner: node_exporter
    mode: 0755
    remote_src: true
  notify: Restart node_exporter

- name: Copy node_exporter.service
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  notify: Reload systemd daemon

- name: Enable node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true

- name: Node_exporter healthcheck
  ansible.builtin.wait_for:
    host: '{{ node_exporter_host }}'
    port: '{{ node_exporter_port }}'
    delay: 5
    timeout: 300
